INTERVAL_SECONDS = 90

WIFI_SSID = "YOUR_SSID"
WIFI_PASSWORD = "YOUR_PASSWORD"

BASE_URL = "http://YOUR_BASE_URL"
ROOM_ID = 0
ROOM_INFO_ID = 0

CF_ACCOUNT_ID = "YOUR_CLOUDFLARE_ACCOUNT_ID"
CF_KV_NAMESPACE_ID = "YOUR_KV_NAMESPACE_ID"
CF_API_TOKEN = "YOUR_CLOUDFLARE_API_TOKEN"
CF_KV_KEY = "aircon-settings-v1"
